export const products = [
  {
    id: "P001",
    name: "Sport Runner X",
    price: 59.99,
    description: "Excellent lightweight running shoes with strong grip.",
    image: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.7,
    colors: ["Black", "Gray", "White"],
    available: true,
    category: "Running"
  },
  {
    id: "P002",
    name: "Urban Street Sneaker",
    price: 79.99,
    description: "Comfortable sneakers for casual and modern style.",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.5,
    colors: ["Black", "White", "Red"],
    available: true,
    category: "Casual"
  },
  {
    id: "P003",
    name: "Pro Marathon Shoe",
    price: 99.99,
    description: "High performance running shoes built for marathon training.",
    image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.8,
    colors: ["Black", "Blue", "White"],
    available: true,
    category: "Running"
  },
  {
    id: "P004",
    name: "Classic White Shoes",
    price: 69.99,
    description: "Minimalist white shoes perfect for daily fashion.",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.4,
    colors: ["White", "Black"],
    available: true,
    category: "Casual"
  },
  {
    id: "P005",
    name: "Highland Trek Boots",
    price: 120.99,
    description: "Premium hiking boots suitable for all terrains.",
    image: "https://images.pexels.com/photos/3309893/pexels-photo-3309893.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.7,
    colors: ["Brown", "Black"],
    available: true,
    category: "Hiking"
  },
  {
    id: "P006",
    name: "Comfort Slip-ons",
    price: 49.99,
    description: "Easy slip-on shoes perfect for travel and daily wear.",
    image: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.2,
    colors: ["Black", "White"],
    available: true,
    category: "Casual"
  },
  {
    id: "P007",
    name: "Trail Master Sneakers",
    price: 110.99,
    description: "Durable trail sneakers with excellent shock absorption.",
    image: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.6,
    colors: ["Black", "Green"],
    available: true,
    category: "Trail"
  },
  {
    id: "P008",
    name: "Sporty Mesh Running",
    price: 89.99,
    description: "Breathable mesh runners for daily workouts.",
    image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.4,
    colors: ["Blue", "Black", "Gray"],
    available: true,
    category: "Running"
  },
  {
    id: "P009",
    name: "Everyday Classic Sneaker",
    price: 75.99,
    description: "Modern shoe for everyday street style.",
    image: "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.3,
    colors: ["White", "Blue"],
    available: true,
    category: "Casual"
  },
  {
    id: "P010",
    name: "Elite Jog Runner",
    price: 95.99,
    description: "Engineered running shoes with balanced traction.",
    image: "https://images.pexels.com/photos/3768914/pexels-photo-3768914.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.6,
    colors: ["Black", "Yellow"],
    available: true,
    category: "Running"
  },
  {
    id: "P011",
    name: "Urban Canvas Shoes",
    price: 59.99,
    description: "Canvas casual shoes with breathable comfort.",
    image: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.1,
    colors: ["White", "Gray"],
    available: true,
    category: "Casual"
  },
  {
    id: "P012",
    name: "Outdoor Adventure Boots",
    price: 130.99,
    description: "Heavy-duty boots made for rugged adventure.",
    image: "https://images.pexels.com/photos/3309893/pexels-photo-3309893.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.8,
    colors: ["Brown", "Black"],
    available: true,
    category: "Hiking"
  },
  {
    id: "P013",
    name: "All Day Comfort Shoes",
    price: 80.99,
    description: "Comfort-centric shoes for all-day wear.",
    image: "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.5,
    colors: ["Black", "Blue"],
    available: true,
    category: "Casual"
  },
  {
    id: "P014",
    name: "High Performance Runner",
    price: 102.99,
    description: "Designed for athletes with max comfort.",
    image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.7,
    colors: ["Red", "Gray"],
    available: true,
    category: "Running"
  },
  {
    id: "P015",
    name: "Elegant Formal Shoes",
    price: 99.99,
    description: "Classy formal shoes for sophisticated style.",
    image: "https://images.pexels.com/photos/19090/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.4,
    colors: ["Black", "Brown"],
    available: true,
    category: "Formal"
  },
  {
    id: "P016",
    name: "Comfort Trail Walker",
    price: 85.99,
    description: "Trail shoes for seamless outdoor walks.",
    image: "https://images.pexels.com/photos/3309893/pexels-photo-3309893.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.6,
    colors: ["Green", "Brown"],
    available: true,
    category: "Trail"
  },
  {
    id: "P017",
    name: "Everyday Running Shoe",
    price: 88.99,
    description: "Balanced running shoes for daily jogs.",
    image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.3,
    colors: ["Black", "Orange"],
    available: true,
    category: "Running"
  },
  {
    id: "P018",
    name: "Casual Weekend Sneaker",
    price: 65.99,
    description: "Sneakers designed for weekend hangouts.",
    image: "https://images.pexels.com/photos/292999/pexels-photo-292999.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.2,
    colors: ["White", "Yellow"],
    available: true,
    category: "Casual"
  },
  {
    id: "P019",
    name: "Outdoor Trekking Shoes",
    price: 115.99,
    description: "Durable trekking shoes for outdoor explorers.",
    image: "https://images.pexels.com/photos/3309893/pexels-photo-3309893.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.7,
    colors: ["Brown", "Black"],
    available: true,
    category: "Hiking"
  },
  {
    id: "P020",
    name: "Pro Sports Runner",
    price: 105.99,
    description: "Top-tier running shoes for serious athletes.",
    image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    rating: 4.8,
    colors: ["Black", "Blue"],
    available: true,
    category: "Running"
  }
];